$primary = rgb(8a9a7b)
$surface = rgb(181616)
$secondary = rgb(8ea4a2)
$error = rgb(c4746e)
$tertiary = rgb(c4746e)
$surface_lowest = rgb(1b1919)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
